// Generated by ReScript, PLEASE EDIT WITH CARE


var AnonymousInterface0 = {};

var Unit = {
  AnonymousInterface0: AnonymousInterface0
};

var Export = {
  Unit: undefined
};

export {
  Unit ,
  Export ,
}
/* No side effect */
