// Generated by ReScript, PLEASE EDIT WITH CARE


var X = {};

var AnonymousInterface1 = {};

var AnonymousInterface1$1 = {};

var Name = {
  AnonymousInterface1: AnonymousInterface1$1
};

var Export = {
  Name: undefined,
  X: undefined
};

var Data_Unit;

export {
  Data_Unit ,
  X ,
  AnonymousInterface1 ,
  Name ,
  Export ,
}
/* No side effect */
