// Generated by ReScript, PLEASE EDIT WITH CARE


function usePurs() {
  var pursInstance = {
    name: "John Doe",
    org: "ReScript Association",
    rank: 1.0
  };
  var name = pursInstance.name;
  var org = pursInstance.org;
  var rank = pursInstance.rank;
  console.log("Purs instance:");
  console.log("Name: " + name);
  console.log("Org: " + org);
  console.log("Rank: " + rank.toString());
}

export {
  usePurs ,
}
/* No side effect */
