// Generated by ReScript, PLEASE EDIT WITH CARE


var IUser = {};

var User = {};

var AnonymousInterface0 = {};

var IPurs = {
  AnonymousInterface0: AnonymousInterface0
};

var IProduct = {};

var IAdminUser = {};

export {
  IAdminUser ,
  IProduct ,
  IPurs ,
  IUser ,
  User ,
}
/* No side effect */
